function ChangeGeneSymbols(MarkerSize)
% ChangeGeneSymbols(MarkerSize);
%
% changes gene symbols so in situ plots look nice. 
% MarkerSize defaults to 6 - if 0, won't change existing sizes

if nargin<1
    MarkerSize = 6;
end


% colors
non_neuron = hsv2rgb([0 0 1]);
pc_or_in =   hsv2rgb([.4 .5 .5]);
pc_or_in2 =   hsv2rgb([.3 .2 .7]);
pc =        hsv2rgb([1/3 1 1]);
pc2 =       hsv2rgb([1/4 1 .9]);
in_general = hsv2rgb([2/3 1 1]);

sst =   hsv2rgb([.55 1 1]);
pvalb = hsv2rgb([.7 .8 1]);
ngf =   hsv2rgb([.85 1 1]);
cnr1 =  hsv2rgb([ 1 1 1]);
vip =   hsv2rgb([ .15 1 1]);
cxcl14= hsv2rgb([.1 1 .6]);


% All symbols: +o*.xsd^V<>ph - have them in that order to not get confused
New_symbols = {...
    
    'Snca',     in_general, '+'; ...
    'Scg2',     in_general, 'x'; ...
    'Lhx6',     in_general, 's'; ...
    'Zcchc12',  in_general, '^'; ...
    'Serpini1', in_general, 'v'; ...
    'Gad1',     in_general, 'p'; ...   
    'Slc6a1',   in_general, 'h'; ...
    
    
    'Th',       sst, '+'; ...
    'Crhbp',    sst, 'o'; ...
    'Sst',      sst, '*'; ...
    'Npy',      sst, '.'; ...
    'Synpr',    sst, 'x'; ...
    'Chodl',    sst, 's';...
    'Cort',     sst, 'd'; ...
    'Reln',     sst, '^'; ...
    'Satb1',    sst, '>'; ...
    'Grin3a',   sst, 'p'; ...
    
    'Tac1',     pvalb, 'o'; ...
    'Pvalb',    pvalb, '*'; ...
    'Kcnip2',   pvalb, 's'; ...
    'Thsd7a',   pvalb, 'd'; ...
    'Cox6a2',   pvalb, 'v'; ...
    'Chrm2',    pvalb, 'p'; ...
    
    'Id2',      ngf, '+'; ...
    'Hapln1',   ngf, 'o'; ...
    'Gabrd',    ngf, '*'; ...
    'Kit',      ngf, 's'; ...
    'Ndnf',     ngf, 'd'; ...
    'Nos1',     ngf, '^'; ...
    'Rab3c',    ngf, 'v'; ...
    'Lamp5',    ngf, '>'; ...
    'Cplx3',    ngf, 'h'; ...

    'Cxcl14',   cxcl14, '*'; ...
    'Cpne5',    cxcl14, 'd'; ...
    'Rgs12',    cxcl14, 'h'; ...
  

    'Sncg',     cnr1, 'o'; ...
    'Cnr1',     cnr1, '*'; ...
    'Cck',      cnr1, '.'; ...
    'Sema3c',   cnr1, 's'; ...
    'Fxyd6',    cnr1, 'd'; ...
    'Syt6',     cnr1, '^'; ...
    'Rgs10',    cnr1, '>'; ...
    'Nov',      cnr1, '<'; ...
    'Slc17a8',  cnr1, 'h'; ...
    
    'Calb2',    vip, '*'; ...
    'Npy2r',    vip, 'o'; ...
    'Htr3a',    vip, '.'; ...
    'Slc5a7',   vip, 'x'; ...
    'Tac2',     vip, '+'; ...
    'Pthlh',    vip, '^'; ...
    'Vip',      vip, 'v'; ...
    'Crh',      vip, '>'; ...
    'Qrfpr',    vip, 'p'; ...
    
    'Nrn1',     pc, '*'; ...
    'Pcp4',     pc, '.'; ...
    'Rprm',     pc, '+'; ...
    'Enpp2',    pc, 'x';...
    'Rorb',     pc, 'o'; ...
    'Rasgrf2',  pc, 's'; ...
    'Wfs1',     pc, 'd'; ...
    'Fos',      pc, '>'; ...
    'Plcxd2',   pc, 'v'; ...
    'Crym',     pc, '<'; ...
    '3110035E14Rik', pc, '^'; ...
    'Foxp2',    pc, 'p';...
    'Pvrl3',    pc, 'h'; ...
    
    'Neurod6',  pc2, '+'; ...
    'Nr4a2',    pc2, 'o'; ...
    'Cux2',     pc2, '*'; ...
    'Kcnk2',    pc2, '.'; ...
    'Arpp21',   pc2, 's'; ...
    'Enc1',     pc2, 'v'; ...
    'Fam19a1',  pc2, '>'; ...
    
% All symbols: +o*.xsd^V<>ph - have them in that order to not get confused
    
    'Gda',      pc_or_in, '+'; ...
    'Bcl11b',   pc_or_in, 'o'; ...
    'Cdh13',    pc_or_in, '*'; ...
    'Slc24a2',  pc_or_in, '.'; ...
    'Lphn2',    pc_or_in, 'x'; ...
    'Map2',     pc_or_in, 's'; ...
    'Calb1',    pc_or_in, 'd';...
    'Rgs4',     pc_or_in, '^'; ...
    'Atp1b1',   pc_or_in, 'v'; ...
    'Pde1a',    pc_or_in, '<'; ...
    'Calm2',    pc_or_in, '>'; ...
    'Penk',     pc_or_in, 'p';...
    'Sema3e',   pc_or_in, 'h'; ...
    
    'Gap43',      pc_or_in2, '*'; ...

    
    'Vim',      non_neuron, '*'; ...
    'Slc1a2',   non_neuron, '.'; ...
    'Pax6',     non_neuron, 's'; ...
    'Plp1',     non_neuron, 'x'; ...
    'Mal',      non_neuron, '+'; ...
    'Aldoc',    non_neuron, 'o'; ...
    'Actb',     non_neuron, 'v'; ...
    'Sulf2',    non_neuron, 'p'; ...
    

    
    };

n =  size(New_symbols,1);

gc = get(gca, 'children');
MyChildren = [];
for i=1:length(gc)
    if strcmp(gc(i).Type, 'line') 
%     if strcmp(gc(i).Type, 'scatter')
        MyChildren = [MyChildren; i];
    end
end
DisplayNames = {gc(MyChildren).DisplayName};
% get first word of display name as gene
GeneNames = cell(size(DisplayNames));
for i=1:length(DisplayNames)
    GeneNames{i} = strtok(DisplayNames{i});
end
    
clear h s;
j=1;
for i=1:n
    MyGeneName = New_symbols{i,1};
    l = find(strcmp(MyGeneName, GeneNames));
    if ~isempty(l)
        h(j) = gc(l);
        set(h(j), 'Marker', New_symbols{i,3});
        set(h(j), 'Color', New_symbols{i,2});
%         set(h(j), 'CData', New_symbols{i,2});
        if MarkerSize>0
            set(h(j), 'MarkerSize', MarkerSize);
%             set(h(j), 'SizeData', MarkerSize);
        end
        s(j) = i;
        j=j+1;
    end
end

other_h = setdiff(gc(MyChildren), h);
other_symbols = {other_h.DisplayName};

legend([h(:); other_h(:)], {New_symbols{s,1}, other_symbols{:}}, 'color', [1 1 1]*.7);
set(gcf, 'color', 'k');
set(gcf, 'InvertHardcopy', 'off');
    